# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 10:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idle_app', '0002_game_item_playeritem_usergame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='game',
        ),
        migrations.AddField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idle_app.Game'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='timePlayed',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='user',
        ),
        migrations.AddField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
