# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idle_app', '0003_auto_20170922_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeritem',
            name='game',
        ),
        migrations.AddField(
            model_name='playeritem',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idle_app.Game'),
        ),
        migrations.RemoveField(
            model_name='playeritem',
            name='user',
        ),
        migrations.AddField(
            model_name='playeritem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
